name: 文档/博客 的 Bug报告 ‖ Bug Report for Docs/Blog
description: 用于报告文档/博客Bug ‖ Used to Report Docs/Blog Bugs
title: "[Blog Bug]: "
labels: ["bug"]
body: 
  - type: input
    attributes: 
      label: 出现问题的网页地址 ‖ The URL of the Page with the Problem.
    validations:
      required: true
      
  - type: input
    attributes: 
      label: 浏览器原始UA ‖ Browser Original UA
      description: "请详细填写你遇到问题时使用的浏览器的原始UA，如果你不太明白，请访问 https://tool.ip138.com/useragent/ 并将其中的结果复制在这里。 ‖ Please fill in the original UA of the browser you used when you encountered the problem in detail. If you don't quite understand, please visit https://tool.ip138.com/useragent/ and copy the results here."
    validations:
      required: true
  - type: markdown
    attributes:
      label: 问题描述 ‖ Problem Description
      description: "请具体描述你的操作过程和你的问题，必要时需上传日志或者可以证明你的问题的任何材料（如图片，视频）。请不要询问我“xxx应该如何操作？”，这里只允许问题反馈，如果你需要技术支持，请前往我们的QQ群聊： 806312062 ‖ Please describe your operation process and your problem in detail. If necessary, upload a log or any materials (such as pictures and videos) that can prove your problem. Please don't ask me 'how should xxx operate?' Only question feedback is allowed here. If you need technical support, please go to our QQ group to chat: 806312062."
      